 version: 0.0
 os: linux
 files: 
   - source: /
     destination: /home/ubuntu/edx

 hooks:
    BeforeInstall:
      - location: /install_dependencies
        timeout: 300
        runas: root
      - location: /start_server
        timeout: 300
        runas: root 
    AfterInstall: 
      - location: /start.sh
        timeout: 300
        runas: root
         
