 version: 0.0
 os: linux
 files: 
   - source: /
     destination: /home/ubuntu/devstack

 hooks:
    BeforeInstall:
      - location: install_dependencies
        timeout: 300
        runas: root
      - location: start_server
        timeout: 300
        runas: root
    AfterInstall:
       - location: /home/ubuntu/devstack/start.sh
         timeout: 600
         runas: root
         
